name: Build and Deploy demo

on: [workflow_dispatch]

jobs:
  build-and-deploy-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: demo
          BUILD_SCRIPT: npm install
