name: Release

on:
  pull_request:
    types: [ closed ]

jobs:
  prepare-release:
    if: github.base_ref == 'master' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set major release
        if: contains( github.event.pull_request.labels.*.name, 'release-major')
        run: echo "RELEASE=major" >> $GITHUB_ENV
      - name: Set minor release
        if: contains( github.event.pull_request.labels.*.name, 'release-minor')
        run: echo "RELEASE=minor" >> $GITHUB_ENV
      - name: Set patch release
        if: contains( github.event.pull_request.labels.*.name, 'release-patch')
        run: echo "RELEASE=patch" >> $GITHUB_ENV
      - name: Print release type
        run: echo ${{ env.RELEASE }}
      - name: Check release env
        run: |
          if [[ -z "${{ env.RELEASE }}" ]];
          then
            echo "You need to set a release label on PRs to the main branch"
            exit 1
          else
            exit 0
          fi

      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config user.email "pusher-ci@pusher.com"
          git config user.name "Pusher CI"
          git fetch
          git checkout master

      - name: Bump version
        run: |
          npm version ${{ env.RELEASE }}
          export NEW_VERSION=$(npm show . version)
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo ${{ env.VERSION }}

      - name: Push
        run: git push

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}

  tests:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: npm run codestyle
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}


  publish-npm:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build

      - name: Publish stable
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm}}
